const {sanitizeRedditData} = require('./utils.js');
const SANITIZE_DATA_TEST = [{"kind": "t3", data: {
    "approved_at_utc": null,
        "subreddit": "nba",
        "selftext": "",
        "author_fullname": "t2_r9jb9hx0",
        "saved": false,
        "mod_reason_title": null,
        "gilded": 1,
        "clicked": false,
        "title": "[Highlight] Derrick White barely beats the buzzer and forces a game 7!",
        "link_flair_richtext": [{"e": "text", "t": "Highlight"}],
        "subreddit_name_prefixed": "r/nba",
        "hidden": false,
        "pwls": 6,
        "link_flair_css_class": "highlights",
        "downs": 0,
        "thumbnail_height": null,
        "top_awarded_type": null,
        "hide_score": false,
        "name": "t3_13tq0hw",
        "quarantine": false,
        "link_flair_text_color": "light",
        "upvote_ratio": 0.94,
        "author_flair_background_color": "#edeff1",
        "subreddit_type": "public",
        "ups": 22438,
        "total_awards_received": 9,
        "media_embed": {},
    "thumbnail_width": null,
        "author_flair_template_id": "d1b1bbd8-3feb-11e8-8456-0e2b49227936",
        "is_original_content": false,
        "user_reports": [],
        "secure_media": null,
        "is_reddit_media_domain": false,
        "is_meta": false,
        "category": null,
        "secure_media_embed": {},
    "link_flair_text": "Highlight",
        "can_mod_post": false,
        "score": 22438,
        "approved_by": null,
        "is_created_from_ads_ui": false,
        "author_premium": true,
        "thumbnail": "default",
        "edited": false,
        "author_flair_css_class": "Timberwolves1",
        "author_flair_richtext": [{
        "a": ":min-1:",
        "e": "emoji",
        "u": "https://emoji.redditmedia.com/m5aee64xs4r81_t5_2qo4s/min-1"
    }, {"e": "text", "t": " Timberwolves"}],
        "gildings": {"gid_2": 1, "gid_3": 1},
    "content_categories": null,
        "is_self": false,
        "mod_note": null,
        "created": 1685243783.0,
        "link_flair_type": "richtext",
        "wls": 6,
        "removed_by_category": null,
        "banned_by": null,
        "author_flair_type": "richtext",
        "domain": "streamable.com",
        "allow_live_comments": true,
        "selftext_html": null,
        "likes": null,
        "suggested_sort": null,
        "banned_at_utc": null,
        "url_overridden_by_dest": "https://streamable.com/p0udq1",
        "view_count": null,
        "archived": false,
        "no_follow": false,
        "is_crosspostable": false,
        "pinned": false,
        "over_18": false,
        "all_awardings": [{
        "giver_coin_reward": null,
        "subreddit_id": null,
        "is_new": false,
        "days_of_drip_extension": null,
        "coin_price": 100,
        "id": "award_b4072731-c0fb-4440-adc7-1063d6a5e6a0",
        "penny_donate": null,
        "award_sub_type": "GLOBAL",
        "coin_reward": 0,
        "icon_url": "https://i.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png",
        "days_of_premium": null,
        "tiers_by_required_awardings": null,
        "resized_icons": [{
            "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=16&amp;height=16&amp;auto=webp&amp;v=enabled&amp;s=f162f61ae363f12c02888e737f2cb16c1ef1ec76",
            "width": 16,
            "height": 16
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=32&amp;height=32&amp;auto=webp&amp;v=enabled&amp;s=302682d840033201255a2fe2a105ec45cf67a693",
            "width": 32,
            "height": 32
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=48&amp;height=48&amp;auto=webp&amp;v=enabled&amp;s=f3f42da8b2928719f6af5f911ee64bff5e974e99",
            "width": 48,
            "height": 48
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=64&amp;height=64&amp;auto=webp&amp;v=enabled&amp;s=c7cd07a1e46f052689ccab7ad98a6ae6c817d3fa",
            "width": 64,
            "height": 64
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=128&amp;height=128&amp;auto=webp&amp;v=enabled&amp;s=293a8a8f684b86bd4ecf9c5a02d4fb00fc37a105",
            "width": 128,
            "height": 128
        }],
        "icon_width": 2048,
        "static_icon_width": 2048,
        "start_date": null,
        "is_enabled": true,
        "awardings_required_to_grant_benefits": null,
        "description": "C'est magnifique",
        "end_date": null,
        "sticky_duration_seconds": null,
        "subreddit_coin_reward": 0,
        "count": 1,
        "static_icon_height": 2048,
        "name": "Masterpiece",
        "resized_static_icons": [{
            "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=16&amp;height=16&amp;auto=webp&amp;v=enabled&amp;s=f162f61ae363f12c02888e737f2cb16c1ef1ec76",
            "width": 16,
            "height": 16
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=32&amp;height=32&amp;auto=webp&amp;v=enabled&amp;s=302682d840033201255a2fe2a105ec45cf67a693",
            "width": 32,
            "height": 32
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=48&amp;height=48&amp;auto=webp&amp;v=enabled&amp;s=f3f42da8b2928719f6af5f911ee64bff5e974e99",
            "width": 48,
            "height": 48
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=64&amp;height=64&amp;auto=webp&amp;v=enabled&amp;s=c7cd07a1e46f052689ccab7ad98a6ae6c817d3fa",
            "width": 64,
            "height": 64
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png?width=128&amp;height=128&amp;auto=webp&amp;v=enabled&amp;s=293a8a8f684b86bd4ecf9c5a02d4fb00fc37a105",
            "width": 128,
            "height": 128
        }],
        "icon_format": "PNG",
        "icon_height": 2048,
        "penny_price": 0,
        "award_type": "global",
        "static_icon_url": "https://i.redd.it/award_images/t5_22cerq/2juh333m40n51_Masterpiece.png"
    }, {
        "giver_coin_reward": null,
        "subreddit_id": null,
        "is_new": false,
        "days_of_drip_extension": null,
        "coin_price": 325,
        "id": "award_2bc47247-b107-44a8-a78c-613da21869ff",
        "penny_donate": null,
        "award_sub_type": "GLOBAL",
        "coin_reward": 0,
        "icon_url": "https://www.redditstatic.com/gold/awards/icon/Rocket_512.png",
        "days_of_premium": null,
        "tiers_by_required_awardings": null,
        "resized_icons": [{
            "url": "https://www.redditstatic.com/gold/awards/icon/Rocket_16.png",
            "width": 16,
            "height": 16
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/Rocket_32.png",
            "width": 32,
            "height": 32
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/Rocket_48.png",
            "width": 48,
            "height": 48
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/Rocket_64.png",
            "width": 64,
            "height": 64
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/Rocket_128.png",
            "width": 128,
            "height": 128
        }],
        "icon_width": 512,
        "static_icon_width": 512,
        "start_date": null,
        "is_enabled": true,
        "awardings_required_to_grant_benefits": null,
        "description": "Boldly go where we haven't been in a long, long time.",
        "end_date": null,
        "sticky_duration_seconds": null,
        "subreddit_coin_reward": 0,
        "count": 1,
        "static_icon_height": 512,
        "name": "To The Stars",
        "resized_static_icons": [{
            "url": "https://preview.redd.it/award_images/t5_22cerq/1sof6d93g9e51_ToTheStars.png?width=16&amp;height=16&amp;auto=webp&amp;v=enabled&amp;s=06f2d039483185440c5e566f72737a920237569b",
            "width": 16,
            "height": 16
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/1sof6d93g9e51_ToTheStars.png?width=32&amp;height=32&amp;auto=webp&amp;v=enabled&amp;s=d0ecc136d90892f44d543d59e829c16e5fb88e47",
            "width": 32,
            "height": 32
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/1sof6d93g9e51_ToTheStars.png?width=48&amp;height=48&amp;auto=webp&amp;v=enabled&amp;s=62b08d35d1a520218ef92eba8201ac610dce24d7",
            "width": 48,
            "height": 48
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/1sof6d93g9e51_ToTheStars.png?width=64&amp;height=64&amp;auto=webp&amp;v=enabled&amp;s=380d1eeb5fe919116bbafe61b1aa5a82e83d59c2",
            "width": 64,
            "height": 64
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/1sof6d93g9e51_ToTheStars.png?width=128&amp;height=128&amp;auto=webp&amp;v=enabled&amp;s=28263127cf796e9c53e91fb0a750106e59ac67c0",
            "width": 128,
            "height": 128
        }],
        "icon_format": "APNG",
        "icon_height": 512,
        "penny_price": 0,
        "award_type": "global",
        "static_icon_url": "https://i.redd.it/award_images/t5_22cerq/1sof6d93g9e51_ToTheStars.png"
    }, {
        "giver_coin_reward": null,
        "subreddit_id": null,
        "is_new": false,
        "days_of_drip_extension": null,
        "coin_price": 500,
        "id": "award_2ae56630-cfe0-424e-b810-4945b9145358",
        "penny_donate": null,
        "award_sub_type": "GLOBAL",
        "coin_reward": 100,
        "icon_url": "https://www.redditstatic.com/gold/awards/icon/Animated_Helpful_512.png",
        "days_of_premium": null,
        "tiers_by_required_awardings": null,
        "resized_icons": [{
            "url": "https://www.redditstatic.com/gold/awards/icon/Animated_Helpful_16.png",
            "width": 16,
            "height": 16
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/Animated_Helpful_32.png",
            "width": 32,
            "height": 32
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/Animated_Helpful_48.png",
            "width": 48,
            "height": 48
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/Animated_Helpful_64.png",
            "width": 64,
            "height": 64
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/Animated_Helpful_128.png",
            "width": 128,
            "height": 128
        }],
        "icon_width": 2048,
        "static_icon_width": 2048,
        "start_date": null,
        "is_enabled": true,
        "awardings_required_to_grant_benefits": null,
        "description": "Thank you stranger. Gives %{coin_symbol}100 Coins to both the author and the community.",
        "end_date": null,
        "sticky_duration_seconds": null,
        "subreddit_coin_reward": 100,
        "count": 1,
        "static_icon_height": 2048,
        "name": "Helpful (Pro)",
        "resized_static_icons": [{
            "url": "https://preview.redd.it/award_images/t5_q0gj4/zkc9cw88c8361_ChristmasHelpful.png?width=16&amp;height=16&amp;auto=webp&amp;v=enabled&amp;s=e29d34590f34dd9869dcb86da6d93228cff8764b",
            "width": 16,
            "height": 16
        }, {
            "url": "https://preview.redd.it/award_images/t5_q0gj4/zkc9cw88c8361_ChristmasHelpful.png?width=32&amp;height=32&amp;auto=webp&amp;v=enabled&amp;s=3ea98b679ab75fddaa8f6c6cfd42ea8fae55edcf",
            "width": 32,
            "height": 32
        }, {
            "url": "https://preview.redd.it/award_images/t5_q0gj4/zkc9cw88c8361_ChristmasHelpful.png?width=48&amp;height=48&amp;auto=webp&amp;v=enabled&amp;s=e16700d712db912e08633cdb9bd4eb78e7658660",
            "width": 48,
            "height": 48
        }, {
            "url": "https://preview.redd.it/award_images/t5_q0gj4/zkc9cw88c8361_ChristmasHelpful.png?width=64&amp;height=64&amp;auto=webp&amp;v=enabled&amp;s=55281b48a7355141bf4e7464f5626830be9bce6c",
            "width": 64,
            "height": 64
        }, {
            "url": "https://preview.redd.it/award_images/t5_q0gj4/zkc9cw88c8361_ChristmasHelpful.png?width=128&amp;height=128&amp;auto=webp&amp;v=enabled&amp;s=64e6b2b5257d07985d17f50c3e393c7225f1ecba",
            "width": 128,
            "height": 128
        }],
        "icon_format": "APNG",
        "icon_height": 2048,
        "penny_price": null,
        "award_type": "global",
        "static_icon_url": "https://i.redd.it/award_images/t5_q0gj4/zkc9cw88c8361_ChristmasHelpful.png"
    }, {
        "giver_coin_reward": null,
        "subreddit_id": null,
        "is_new": false,
        "days_of_drip_extension": null,
        "coin_price": 325,
        "id": "award_3409a4c0-ba69-43a0-be9f-27bc27c159cc",
        "penny_donate": null,
        "award_sub_type": "GLOBAL",
        "coin_reward": 0,
        "icon_url": "https://www.redditstatic.com/gold/awards/icon/Spits_drink_512.png",
        "days_of_premium": null,
        "tiers_by_required_awardings": null,
        "resized_icons": [{
            "url": "https://www.redditstatic.com/gold/awards/icon/Spits_drink_16.png",
            "width": 16,
            "height": 16
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/Spits_drink_32.png",
            "width": 32,
            "height": 32
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/Spits_drink_48.png",
            "width": 48,
            "height": 48
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/Spits_drink_64.png",
            "width": 64,
            "height": 64
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/Spits_drink_128.png",
            "width": 128,
            "height": 128
        }],
        "icon_width": 512,
        "static_icon_width": 512,
        "start_date": null,
        "is_enabled": true,
        "awardings_required_to_grant_benefits": null,
        "description": "Shower them with laughs",
        "end_date": null,
        "sticky_duration_seconds": null,
        "subreddit_coin_reward": 0,
        "count": 1,
        "static_icon_height": 512,
        "name": "Spit-take",
        "resized_static_icons": [{
            "url": "https://preview.redd.it/award_images/t5_22cerq/5virpo8iwsj51_Spit-take.png?width=16&amp;height=16&amp;auto=webp&amp;v=enabled&amp;s=ee01f9e3baa051166a156a750531e3aff6e47d7a",
            "width": 16,
            "height": 16
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/5virpo8iwsj51_Spit-take.png?width=32&amp;height=32&amp;auto=webp&amp;v=enabled&amp;s=09692b7458f5cc3b4a5d3553758f471be38c3751",
            "width": 32,
            "height": 32
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/5virpo8iwsj51_Spit-take.png?width=48&amp;height=48&amp;auto=webp&amp;v=enabled&amp;s=621d7dfd289fbaf4434212ff7a65ed59e45f541a",
            "width": 48,
            "height": 48
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/5virpo8iwsj51_Spit-take.png?width=64&amp;height=64&amp;auto=webp&amp;v=enabled&amp;s=9c34545da7cb553cab0df7fadcd77899be0d96b1",
            "width": 64,
            "height": 64
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/5virpo8iwsj51_Spit-take.png?width=128&amp;height=128&amp;auto=webp&amp;v=enabled&amp;s=039d54066249c020d613ea8ccb96bca72d3d6e31",
            "width": 128,
            "height": 128
        }],
        "icon_format": "APNG",
        "icon_height": 512,
        "penny_price": 0,
        "award_type": "global",
        "static_icon_url": "https://i.redd.it/award_images/t5_22cerq/5virpo8iwsj51_Spit-take.png"
    }, {
        "giver_coin_reward": null,
        "subreddit_id": null,
        "is_new": false,
        "days_of_drip_extension": null,
        "coin_price": 500,
        "id": "gid_2",
        "penny_donate": null,
        "award_sub_type": "GLOBAL",
        "coin_reward": 100,
        "icon_url": "https://www.redditstatic.com/gold/awards/icon/gold_512.png",
        "days_of_premium": 7,
        "tiers_by_required_awardings": null,
        "resized_icons": [{
            "url": "https://www.redditstatic.com/gold/awards/icon/gold_16.png",
            "width": 16,
            "height": 16
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/gold_32.png",
            "width": 32,
            "height": 32
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/gold_48.png",
            "width": 48,
            "height": 48
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/gold_64.png",
            "width": 64,
            "height": 64
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/gold_128.png",
            "width": 128,
            "height": 128
        }],
        "icon_width": 512,
        "static_icon_width": 512,
        "start_date": null,
        "is_enabled": true,
        "awardings_required_to_grant_benefits": null,
        "description": "Gives 100 Reddit Coins and a week of r/lounge access and ad-free browsing.",
        "end_date": null,
        "sticky_duration_seconds": null,
        "subreddit_coin_reward": 0,
        "count": 1,
        "static_icon_height": 512,
        "name": "Gold",
        "resized_static_icons": [{
            "url": "https://www.redditstatic.com/gold/awards/icon/gold_16.png",
            "width": 16,
            "height": 16
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/gold_32.png",
            "width": 32,
            "height": 32
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/gold_48.png",
            "width": 48,
            "height": 48
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/gold_64.png",
            "width": 64,
            "height": 64
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/gold_128.png",
            "width": 128,
            "height": 128
        }],
        "icon_format": null,
        "icon_height": 512,
        "penny_price": null,
        "award_type": "global",
        "static_icon_url": "https://www.redditstatic.com/gold/awards/icon/gold_512.png"
    }, {
        "giver_coin_reward": null,
        "subreddit_id": null,
        "is_new": false,
        "days_of_drip_extension": 31,
        "coin_price": 1800,
        "id": "gid_3",
        "penny_donate": null,
        "award_sub_type": "GLOBAL",
        "coin_reward": 0,
        "icon_url": "https://www.redditstatic.com/gold/awards/icon/platinum_512.png",
        "days_of_premium": 31,
        "tiers_by_required_awardings": null,
        "resized_icons": [{
            "url": "https://www.redditstatic.com/gold/awards/icon/platinum_16.png",
            "width": 16,
            "height": 16
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/platinum_32.png",
            "width": 32,
            "height": 32
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/platinum_48.png",
            "width": 48,
            "height": 48
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/platinum_64.png",
            "width": 64,
            "height": 64
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/platinum_128.png",
            "width": 128,
            "height": 128
        }],
        "icon_width": 512,
        "static_icon_width": 512,
        "start_date": null,
        "is_enabled": true,
        "awardings_required_to_grant_benefits": null,
        "description": "Gives 700 Reddit Coins and a month of r/lounge access and ad-free browsing.",
        "end_date": null,
        "sticky_duration_seconds": null,
        "subreddit_coin_reward": 0,
        "count": 1,
        "static_icon_height": 512,
        "name": "Platinum",
        "resized_static_icons": [{
            "url": "https://www.redditstatic.com/gold/awards/icon/platinum_16.png",
            "width": 16,
            "height": 16
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/platinum_32.png",
            "width": 32,
            "height": 32
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/platinum_48.png",
            "width": 48,
            "height": 48
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/platinum_64.png",
            "width": 64,
            "height": 64
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/platinum_128.png",
            "width": 128,
            "height": 128
        }],
        "icon_format": null,
        "icon_height": 512,
        "penny_price": null,
        "award_type": "global",
        "static_icon_url": "https://www.redditstatic.com/gold/awards/icon/platinum_512.png"
    }, {
        "giver_coin_reward": null,
        "subreddit_id": null,
        "is_new": false,
        "days_of_drip_extension": null,
        "coin_price": 250,
        "id": "award_435a5692-f508-4b31-8083-ddc576f26ad3",
        "penny_donate": null,
        "award_sub_type": "GLOBAL",
        "coin_reward": 0,
        "icon_url": "https://www.redditstatic.com/gold/awards/icon/hehehe_b_512.png",
        "days_of_premium": null,
        "tiers_by_required_awardings": null,
        "resized_icons": [{
            "url": "https://www.redditstatic.com/gold/awards/icon/hehehe_b_16.png",
            "width": 16,
            "height": 16
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/hehehe_b_32.png",
            "width": 32,
            "height": 32
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/hehehe_b_48.png",
            "width": 48,
            "height": 48
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/hehehe_b_64.png",
            "width": 64,
            "height": 64
        }, {
            "url": "https://www.redditstatic.com/gold/awards/icon/hehehe_b_128.png",
            "width": 128,
            "height": 128
        }],
        "icon_width": 512,
        "static_icon_width": 512,
        "start_date": null,
        "is_enabled": true,
        "awardings_required_to_grant_benefits": null,
        "description": "That's a little funny",
        "end_date": null,
        "sticky_duration_seconds": null,
        "subreddit_coin_reward": 0,
        "count": 1,
        "static_icon_height": 512,
        "name": "hehehehe",
        "resized_static_icons": [{
            "url": "https://preview.redd.it/award_images/t5_22cerq/zenxchy18kd61_hehehehe.png?width=16&amp;height=16&amp;auto=webp&amp;v=enabled&amp;s=6cc14bb007fae14f0e75f5a89436b267e014db4c",
            "width": 16,
            "height": 16
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/zenxchy18kd61_hehehehe.png?width=32&amp;height=32&amp;auto=webp&amp;v=enabled&amp;s=1c7ad59dd1f6239b4836d5c457742b5f4bc94896",
            "width": 32,
            "height": 32
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/zenxchy18kd61_hehehehe.png?width=48&amp;height=48&amp;auto=webp&amp;v=enabled&amp;s=86c3d633a3ad6d639de7ca3a09e987a96880e528",
            "width": 48,
            "height": 48
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/zenxchy18kd61_hehehehe.png?width=64&amp;height=64&amp;auto=webp&amp;v=enabled&amp;s=c21fa1e1b3a6d3268b9da46ea0e5860c35667107",
            "width": 64,
            "height": 64
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/zenxchy18kd61_hehehehe.png?width=128&amp;height=128&amp;auto=webp&amp;v=enabled&amp;s=a6f9da4256b819dc093f495531501d725d80affe",
            "width": 128,
            "height": 128
        }],
        "icon_format": "APNG",
        "icon_height": 512,
        "penny_price": 0,
        "award_type": "global",
        "static_icon_url": "https://i.redd.it/award_images/t5_22cerq/zenxchy18kd61_hehehehe.png"
    }, {
        "giver_coin_reward": null,
        "subreddit_id": null,
        "is_new": false,
        "days_of_drip_extension": null,
        "coin_price": 100,
        "id": "award_19860e30-3331-4bac-b3d1-bd28de0c7974",
        "penny_donate": null,
        "award_sub_type": "GLOBAL",
        "coin_reward": 0,
        "icon_url": "https://i.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png",
        "days_of_premium": null,
        "tiers_by_required_awardings": null,
        "resized_icons": [{
            "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=16&amp;height=16&amp;auto=webp&amp;v=enabled&amp;s=7434e8ec65f434b811666ff6be1cbc18e675c5bf",
            "width": 16,
            "height": 16
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=32&amp;height=32&amp;auto=webp&amp;v=enabled&amp;s=aacfdc98efb123d6d4464d6a227aff2f9d90a3fb",
            "width": 32,
            "height": 32
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=48&amp;height=48&amp;auto=webp&amp;v=enabled&amp;s=af6b886c9a013bed09f09ef8bb3757f14a1286b9",
            "width": 48,
            "height": 48
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=64&amp;height=64&amp;auto=webp&amp;v=enabled&amp;s=0e3debe040221236e3cdde5840d9ea8f67d7dca9",
            "width": 64,
            "height": 64
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=128&amp;height=128&amp;auto=webp&amp;v=enabled&amp;s=bd5fb5fe09c1ac5e0d58faed4fc7e9108f6f7718",
            "width": 128,
            "height": 128
        }],
        "icon_width": 2048,
        "static_icon_width": 2048,
        "start_date": null,
        "is_enabled": true,
        "awardings_required_to_grant_benefits": null,
        "description": "I needed this today",
        "end_date": null,
        "sticky_duration_seconds": null,
        "subreddit_coin_reward": 0,
        "count": 2,
        "static_icon_height": 2048,
        "name": "Heartwarming",
        "resized_static_icons": [{
            "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=16&amp;height=16&amp;auto=webp&amp;v=enabled&amp;s=7434e8ec65f434b811666ff6be1cbc18e675c5bf",
            "width": 16,
            "height": 16
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=32&amp;height=32&amp;auto=webp&amp;v=enabled&amp;s=aacfdc98efb123d6d4464d6a227aff2f9d90a3fb",
            "width": 32,
            "height": 32
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=48&amp;height=48&amp;auto=webp&amp;v=enabled&amp;s=af6b886c9a013bed09f09ef8bb3757f14a1286b9",
            "width": 48,
            "height": 48
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=64&amp;height=64&amp;auto=webp&amp;v=enabled&amp;s=0e3debe040221236e3cdde5840d9ea8f67d7dca9",
            "width": 64,
            "height": 64
        }, {
            "url": "https://preview.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png?width=128&amp;height=128&amp;auto=webp&amp;v=enabled&amp;s=bd5fb5fe09c1ac5e0d58faed4fc7e9108f6f7718",
            "width": 128,
            "height": 128
        }],
        "icon_format": "PNG",
        "icon_height": 2048,
        "penny_price": 0,
        "award_type": "global",
        "static_icon_url": "https://i.redd.it/award_images/t5_22cerq/v1mxw8i6wnf51_Heartwarming.png"
    }],
        "awarders": [],
        "media_only": false,
        "link_flair_template_id": "11e1d3fc-5c54-11e4-8ccc-12313b0e448d",
        "can_gild": false,
        "spoiler": false,
        "locked": false,
        "author_flair_text": ":min-1: Timberwolves",
        "treatment_tags": [],
        "visited": false,
        "removed_by": null,
        "num_reports": null,
        "distinguished": null,
        "subreddit_id": "t5_2qo4s",
        "author_is_blocked": false,
        "mod_reason_by": null,
        "removal_reason": null,
        "link_flair_background_color": "#ffa500",
        "id": "13tq0hw",
        "is_robot_indexable": true,
        "report_reasons": null,
        "author": "Thimit22",
        "discussion_type": null,
        "num_comments": 2375,
        "send_replies": true,
        "whitelist_status": "all_ads",
        "contest_mode": false,
        "mod_reports": [],
        "author_patreon_flair": false,
        "author_flair_text_color": "dark",
        "permalink": "/r/nba/comments/13tq0hw/highlight_derrick_white_barely_beats_the_buzzer/",
        "parent_whitelist_status": "all_ads",
        "stickied": false,
        "url": "https://streamable.com/p0udq1",
        "subreddit_subscribers": 7567308,
        "created_utc": 1685243783.0,
        "num_crossposts": 6,
        "media": null,
        "is_video": false}}];

describe('sanitizeRedditData', () => {

    it('retrieve the correct data from the JSON',async ()=>{
        //part of the subreddit NBA top posts, check if it can sanitize it correctly
        //which means the function should get only the title and the url
        const exampleJsonData = {
            children:
                SANITIZE_DATA_TEST
        };
        const expectedOutput = [["[Highlight] Derrick White barely beats the buzzer and forces a game 7!",
            "https://streamable.com/p0udq1"]];

        const result = sanitizeRedditData(exampleJsonData);
        expect(result).toEqual(expectedOutput);
    });

    it('return null for empty data',async ()=>{
        //part of the subreddit NBA top posts, check if it can sanitize it correctly
        //which means the function should get only the title and the url
        const exampleJsonData = null;
        const expectedOutput = null;

        const result = sanitizeRedditData(exampleJsonData);
        expect(result).toEqual(expectedOutput);
    });

    it('return null for invalid data',async ()=>{
        //part of the subreddit NBA top posts, check if it can sanitize it correctly
        //which means the function should get only the title and the url
        const exampleJsonData = ['bla'];
        const expectedOutput = null;

        const result = sanitizeRedditData(exampleJsonData);
        expect(result).toEqual(expectedOutput);
    });
});
